### ISSUE TITLE
elegantBI Addition

### ISSUE THREAD

**Issue by jfallt** [NajiElKotob/Awesome-Power-BI#2]
Didn't see this on the list of resources, i'm a big fan of the tabular editor articles.
https://www.elegantbi.com/

**Comment by NajiElKotob** [comment]
Thank you, actually we didn't find any good reference or a benchmark. If you have a good reference from a third party please share.

**Comment by GonzoJrETU** [comment]
I apologize for not getting back to you.
Thank you for your quick reply. We haven’t found anything that would circumvent or force the sql to the level of using choosing the index to use for the query, in a dynamic way.

Thank you.
jorge
